[2023-01-23T15:48:31.470+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_14.extract_data manual__2023-01-23T15:48:29.885880+00:00 [queued]>
[2023-01-23T15:48:31.477+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_14.extract_data manual__2023-01-23T15:48:29.885880+00:00 [queued]>
[2023-01-23T15:48:31.478+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T15:48:31.479+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-01-23T15:48:31.479+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T15:48:31.487+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_data> on 2023-01-23 15:48:29.885880+00:00
[2023-01-23T15:48:31.492+0000] {standard_task_runner.py:55} INFO - Started process 4127 to run task
[2023-01-23T15:48:31.495+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_and_loading_14', 'extract_data', 'manual__2023-01-23T15:48:29.885880+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpz4_0xss7']
[2023-01-23T15:48:31.499+0000] {standard_task_runner.py:83} INFO - Job 145: Subtask extract_data
[2023-01-23T15:48:31.513+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-23T15:48:31.561+0000] {task_command.py:388} INFO - Running <TaskInstance: data_extraction_and_loading_14.extract_data manual__2023-01-23T15:48:29.885880+00:00 [running]> on host 1b696c32fad4
[2023-01-23T15:48:31.605+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_extraction_and_loading_14
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T15:48:29.885880+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T15:48:29.885880+00:00
[2023-01-23T15:49:11.841+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 15, in extract_data
    pickled_data_extractor = pickle.dumps(data_extractor)
AttributeError: Can't pickle local object 'PoolManager.__init__.<locals>.<lambda>'
[2023-01-23T15:49:11.865+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_and_loading_14, task_id=extract_data, execution_date=20230123T154829, start_date=20230123T154831, end_date=20230123T154911
[2023-01-23T15:49:11.884+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 145 for task extract_data (Can't pickle local object 'PoolManager.__init__.<locals>.<lambda>'; 4127)
[2023-01-23T15:49:11.934+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-23T15:49:11.965+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
