[2023-01-29T21:21:08.568+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_1.extract_data_task_data_engineer manual__2023-01-29T21:20:46.454488+00:00 [queued]>
[2023-01-29T21:21:08.590+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_1.extract_data_task_data_engineer manual__2023-01-29T21:20:46.454488+00:00 [queued]>
[2023-01-29T21:21:08.590+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T21:21:08.591+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-01-29T21:21:08.591+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T21:21:08.618+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_data_task_data_engineer> on 2023-01-29 21:20:46.454488+00:00
[2023-01-29T21:21:08.656+0000] {standard_task_runner.py:55} INFO - Started process 2376 to run task
[2023-01-29T21:21:08.665+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_1', 'extract_data_task_data_engineer', 'manual__2023-01-29T21:20:46.454488+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpgqjgzsa5']
[2023-01-29T21:21:08.684+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask extract_data_task_data_engineer
[2023-01-29T21:21:08.757+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-29T21:21:09.126+0000] {task_command.py:388} INFO - Running <TaskInstance: data_pipeline_1.extract_data_task_data_engineer manual__2023-01-29T21:20:46.454488+00:00 [running]> on host 84fb6dd1372f
[2023-01-29T21:21:09.427+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_pipeline_1
AIRFLOW_CTX_TASK_ID=extract_data_task_data_engineer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T21:20:46.454488+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-29T21:20:46.454488+00:00
[2023-01-29T21:21:40.727+0000] {etl.py:120} ERROR - Error
[2023-01-29T21:21:40.760+0000] {etl.py:120} ERROR - Error
[2023-01-29T21:21:40.797+0000] {etl.py:120} ERROR - Error
[2023-01-29T21:21:40.848+0000] {etl.py:120} ERROR - Error
[2023-01-29T21:21:40.894+0000] {etl.py:120} ERROR - Error
[2023-01-29T21:21:40.950+0000] {etl.py:120} ERROR - Error
[2023-01-29T21:21:41.472+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-29T21:21:41.512+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=data_pipeline_1, task_id=extract_data_task_data_engineer, execution_date=20230129T212046, start_date=20230129T212108, end_date=20230129T212141
[2023-01-29T21:21:41.641+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-29T21:21:41.835+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
