[2023-01-29T20:57:58.546+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline.extract_data_task_data_engineer manual__2023-01-29T20:57:35.243338+00:00 [queued]>
[2023-01-29T20:57:58.562+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline.extract_data_task_data_engineer manual__2023-01-29T20:57:35.243338+00:00 [queued]>
[2023-01-29T20:57:58.563+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T20:57:58.563+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-01-29T20:57:58.563+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T20:57:58.589+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_data_task_data_engineer> on 2023-01-29 20:57:35.243338+00:00
[2023-01-29T20:57:58.600+0000] {standard_task_runner.py:55} INFO - Started process 1910 to run task
[2023-01-29T20:57:58.611+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'extract_data_task_data_engineer', 'manual__2023-01-29T20:57:35.243338+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpm26wjf0b']
[2023-01-29T20:57:58.615+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask extract_data_task_data_engineer
[2023-01-29T20:57:58.649+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-29T20:57:58.733+0000] {task_command.py:388} INFO - Running <TaskInstance: data_pipeline.extract_data_task_data_engineer manual__2023-01-29T20:57:35.243338+00:00 [running]> on host 84fb6dd1372f
[2023-01-29T20:57:58.915+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=extract_data_task_data_engineer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T20:57:35.243338+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-29T20:57:35.243338+00:00
[2023-01-29T20:58:29.388+0000] {etl.py:120} ERROR - Error
[2023-01-29T20:58:29.473+0000] {etl.py:120} ERROR - Error
[2023-01-29T20:58:29.557+0000] {etl.py:120} ERROR - Error
[2023-01-29T20:58:29.616+0000] {etl.py:120} ERROR - Error
[2023-01-29T20:58:29.738+0000] {etl.py:120} ERROR - Error
[2023-01-29T20:58:30.960+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-29T20:58:30.989+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=extract_data_task_data_engineer, execution_date=20230129T205735, start_date=20230129T205758, end_date=20230129T205830
[2023-01-29T20:58:31.059+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-29T20:58:31.145+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
